[build]
  ignore = "exit 1"
  base = "pancake-swap-interface-v1"
  publish = "build"
  command = ""

[build.environment]
  REACT_APP_CHAIN_ID = "97"
  REACT_APP_NETWORK_URL = "https://data-seed-prebsc-1-s1.binance.org:8545"
  